server:
  port: 9091

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackuri: forward:/productServiceFallBack
        - id: SELLER-SERVICE
          uri: lb://SELLER-SERVICE
          predicates:
            - Path=/sellers/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: SELLER-SERVICE
#                fallbackuri: forward:/sellerServiceFallBack



      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      preferIpAddress: true
