server:
  port: 8084

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/e-auction
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect